Repository Los-ultimos/Los-ultimos, pull requests merged in 2021-12, with the labels that each got.

#34 Formulario de generacion de reporte de datos
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/formemail/formemail.component.html
  src/app/formreporte/formreporte.component.css
  src/app/formreporte/formreporte.component.html
  src/app/formreporte/formreporte.component.spec.ts
  src/app/formreporte/formreporte.component.ts
Labels: Size:L, Sprint 4

#44 screanshot de las api
  imagenesWiki/API/screanshotapi1.png
  imagenesWiki/API/screanshotapi2.png
  imagenesWiki/API/screanshotapi3.png
  imagenesWiki/API/screanshotapi4.png
  imagenesWiki/API/screanshotapi5.png
  imagenesWiki/API/screanshotapi6.png
Labels: Size:L, Sprint 4

#52 Reportes funcionando
  backend/app.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/main-hub/dialogs/register-atencion/register-atencion.component.css
  frontend/src/app/models/reporte.model.ts
  frontend/src/app/reportes/dialogform/dialogform.component.html
  frontend/src/app/reportes/dialogform/dialogform.component.ts
  frontend/src/app/reportes/reportes.component.css
  frontend/src/app/reportes/reportes.component.html
  frontend/src/app/reportes/reportes.component.ts
  frontend/src/app/services/reporte.service.spec.ts
  frontend/src/app/services/reporte.service.ts
Labels: Size:L, Sprint 5

#54 Tercer parcial
  backend/app.js
  backend/check-auth.js
  backend/models/user.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/header/header.component.html
  frontend/src/app/header/header.component.ts
  frontend/src/app/login/login.component.html
  frontend/src/app/login/login.component.ts
  frontend/src/app/main-hub/user-info/user-animales/user-animales.component.ts
  frontend/src/app/main-hub/user-info/user-atencion/user-atencion.component.ts
  frontend/src/app/main-hub/user-info/user-decesos/user-decesos.component.ts
  frontend/src/app/main-hub/user-info/user-fichas/user-fichas.component.ts
  frontend/src/app/main-hub/user/user.component.css
  frontend/src/app/main-hub/user/user.component.ts
  frontend/src/app/models/reporte.model.ts
  frontend/src/app/reportes/dialogform/dialogform.component.css
  frontend/src/app/reportes/dialogform/dialogform.component.html
  frontend/src/app/reportes/dialogform/dialogform.component.ts
  frontend/src/app/reportes/reportes.component.css
  frontend/src/app/reportes/reportes.component.html
  frontend/src/app/reportes/reportes.component.ts
  frontend/src/app/services/auth.service.ts
  frontend/src/app/services/reporte.service.ts
  frontend/src/app/services/route.service.ts
  frontend/src/app/user-hub/auth-data.model.ts
  frontend/src/app/user-hub/auth-interceptor.ts
  frontend/src/app/user-hub/auth.guard.ts
  frontend/src/app/user-hub/dialogs/user-edit/user-edit.component.css
  frontend/src/app/user-hub/dialogs/user-edit/user-edit.component.html
  frontend/src/app/user-hub/dialogs/user-edit/user-edit.component.spec.ts
  frontend/src/app/user-hub/dialogs/user-edit/user-edit.component.ts
  frontend/src/app/user-hub/dialogs/user-register/user-register.component.css
  frontend/src/app/user-hub/dialogs/user-register/user-register.component.html
  frontend/src/app/user-hub/dialogs/user-register/user-register.component.spec.ts
  frontend/src/app/user-hub/dialogs/user-register/user-register.component.ts
  frontend/src/app/user-hub/user-hub.component.css
  frontend/src/app/user-hub/user-hub.component.html
  frontend/src/app/user-hub/user-hub.component.spec.ts
  frontend/src/app/user-hub/user-hub.component.ts
  frontend/src/app/user-hub/user-list/user-list.component.css
  frontend/src/app/user-hub/user-list/user-list.component.html
  frontend/src/app/user-hub/user-list/user-list.component.spec.ts
  frontend/src/app/user-hub/user-list/user-list.component.ts
Labels: Size:L, Sprint 6
